/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSubscriptionPlansRouteImport } from './routes/_protected/subscription-plans'
import { Route as ProtectedInquiriesRouteImport } from './routes/_protected/inquiries'
import { Route as ProtectedAuditLogRouteImport } from './routes/_protected/audit-log'
import { Route as ProtectedSupportTicketsIndexRouteImport } from './routes/_protected/support-tickets.index'
import { Route as ProtectedSupportTicketsTicketIdRouteImport } from './routes/_protected/support-tickets.$ticketId'
import { Route as ProtectedInquiriesInquiryIdRouteImport } from './routes/_protected/inquiries.$inquiryId'
import { Route as ProtectedBusinessesBusinessIdRouteImport } from './routes/_protected/businesses.$businessId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSubscriptionPlansRoute =
  ProtectedSubscriptionPlansRouteImport.update({
    id: '/subscription-plans',
    path: '/subscription-plans',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInquiriesRoute = ProtectedInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAuditLogRoute = ProtectedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSupportTicketsIndexRoute =
  ProtectedSupportTicketsIndexRouteImport.update({
    id: '/support-tickets/',
    path: '/support-tickets/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSupportTicketsTicketIdRoute =
  ProtectedSupportTicketsTicketIdRouteImport.update({
    id: '/support-tickets/$ticketId',
    path: '/support-tickets/$ticketId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInquiriesInquiryIdRoute =
  ProtectedInquiriesInquiryIdRouteImport.update({
    id: '/$inquiryId',
    path: '/$inquiryId',
    getParentRoute: () => ProtectedInquiriesRoute,
  } as any)
const ProtectedBusinessesBusinessIdRoute =
  ProtectedBusinessesBusinessIdRouteImport.update({
    id: '/businesses/$businessId',
    path: '/businesses/$businessId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/audit-log': typeof ProtectedAuditLogRoute
  '/inquiries': typeof ProtectedInquiriesRouteWithChildren
  '/subscription-plans': typeof ProtectedSubscriptionPlansRoute
  '/businesses/$businessId': typeof ProtectedBusinessesBusinessIdRoute
  '/inquiries/$inquiryId': typeof ProtectedInquiriesInquiryIdRoute
  '/support-tickets/$ticketId': typeof ProtectedSupportTicketsTicketIdRoute
  '/support-tickets/': typeof ProtectedSupportTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit-log': typeof ProtectedAuditLogRoute
  '/inquiries': typeof ProtectedInquiriesRouteWithChildren
  '/subscription-plans': typeof ProtectedSubscriptionPlansRoute
  '/': typeof ProtectedIndexRoute
  '/businesses/$businessId': typeof ProtectedBusinessesBusinessIdRoute
  '/inquiries/$inquiryId': typeof ProtectedInquiriesInquiryIdRoute
  '/support-tickets/$ticketId': typeof ProtectedSupportTicketsTicketIdRoute
  '/support-tickets': typeof ProtectedSupportTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/audit-log': typeof ProtectedAuditLogRoute
  '/_protected/inquiries': typeof ProtectedInquiriesRouteWithChildren
  '/_protected/subscription-plans': typeof ProtectedSubscriptionPlansRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/businesses/$businessId': typeof ProtectedBusinessesBusinessIdRoute
  '/_protected/inquiries/$inquiryId': typeof ProtectedInquiriesInquiryIdRoute
  '/_protected/support-tickets/$ticketId': typeof ProtectedSupportTicketsTicketIdRoute
  '/_protected/support-tickets/': typeof ProtectedSupportTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-log'
    | '/inquiries'
    | '/subscription-plans'
    | '/businesses/$businessId'
    | '/inquiries/$inquiryId'
    | '/support-tickets/$ticketId'
    | '/support-tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit-log'
    | '/inquiries'
    | '/subscription-plans'
    | '/'
    | '/businesses/$businessId'
    | '/inquiries/$inquiryId'
    | '/support-tickets/$ticketId'
    | '/support-tickets'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/audit-log'
    | '/_protected/inquiries'
    | '/_protected/subscription-plans'
    | '/_protected/'
    | '/_protected/businesses/$businessId'
    | '/_protected/inquiries/$inquiryId'
    | '/_protected/support-tickets/$ticketId'
    | '/_protected/support-tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/subscription-plans': {
      id: '/_protected/subscription-plans'
      path: '/subscription-plans'
      fullPath: '/subscription-plans'
      preLoaderRoute: typeof ProtectedSubscriptionPlansRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inquiries': {
      id: '/_protected/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof ProtectedInquiriesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/audit-log': {
      id: '/_protected/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof ProtectedAuditLogRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/support-tickets/': {
      id: '/_protected/support-tickets/'
      path: '/support-tickets'
      fullPath: '/support-tickets/'
      preLoaderRoute: typeof ProtectedSupportTicketsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/support-tickets/$ticketId': {
      id: '/_protected/support-tickets/$ticketId'
      path: '/support-tickets/$ticketId'
      fullPath: '/support-tickets/$ticketId'
      preLoaderRoute: typeof ProtectedSupportTicketsTicketIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inquiries/$inquiryId': {
      id: '/_protected/inquiries/$inquiryId'
      path: '/$inquiryId'
      fullPath: '/inquiries/$inquiryId'
      preLoaderRoute: typeof ProtectedInquiriesInquiryIdRouteImport
      parentRoute: typeof ProtectedInquiriesRoute
    }
    '/_protected/businesses/$businessId': {
      id: '/_protected/businesses/$businessId'
      path: '/businesses/$businessId'
      fullPath: '/businesses/$businessId'
      preLoaderRoute: typeof ProtectedBusinessesBusinessIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedInquiriesRouteChildren {
  ProtectedInquiriesInquiryIdRoute: typeof ProtectedInquiriesInquiryIdRoute
}

const ProtectedInquiriesRouteChildren: ProtectedInquiriesRouteChildren = {
  ProtectedInquiriesInquiryIdRoute: ProtectedInquiriesInquiryIdRoute,
}

const ProtectedInquiriesRouteWithChildren =
  ProtectedInquiriesRoute._addFileChildren(ProtectedInquiriesRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAuditLogRoute: typeof ProtectedAuditLogRoute
  ProtectedInquiriesRoute: typeof ProtectedInquiriesRouteWithChildren
  ProtectedSubscriptionPlansRoute: typeof ProtectedSubscriptionPlansRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedBusinessesBusinessIdRoute: typeof ProtectedBusinessesBusinessIdRoute
  ProtectedSupportTicketsTicketIdRoute: typeof ProtectedSupportTicketsTicketIdRoute
  ProtectedSupportTicketsIndexRoute: typeof ProtectedSupportTicketsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAuditLogRoute: ProtectedAuditLogRoute,
  ProtectedInquiriesRoute: ProtectedInquiriesRouteWithChildren,
  ProtectedSubscriptionPlansRoute: ProtectedSubscriptionPlansRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedBusinessesBusinessIdRoute: ProtectedBusinessesBusinessIdRoute,
  ProtectedSupportTicketsTicketIdRoute: ProtectedSupportTicketsTicketIdRoute,
  ProtectedSupportTicketsIndexRoute: ProtectedSupportTicketsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
